name: Run Bet365 Bot

on:
  schedule:
    # Executa 3 vezes ao dia: 8h, 14h e 20h (UTC)
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install colorama pandas python-telegram-bot aiohttp requests

    - name: Create config from environment variables
      run: |
        cat > config.py << EOF
        import os
        BOT_TOKEN = os.environ.get("BOT_TOKEN")
        CHAT_ID = os.environ.get("CHAT_ID")
        
        if not BOT_TOKEN or not CHAT_ID:
            raise ValueError("BOT_TOKEN or CHAT_ID environment variables not set")
        EOF

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python run_full_bot.py

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bot-logs-${{ github.run_id }}
        path: run_all_*.log