name: Run Bet365 Bot

on:
  schedule:
    - cron: '0 8 * * *'   # 8:00 UTC
    - cron: '0 14 * * *'  # 14:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC
  workflow_dispatch:      # Permite execução manual

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install colorama pandas python-telegram-bot aiohttp requests python-dotenv
        fi

    - name: Create .env file
      run: |
        cat > .env << EOF
        TELEGRAM_BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        TELEGRAM_CHAT_ID=${{ secrets.CHAT_ID }}
        BETSAPI_API_KEY=${{ secrets.BETS_API_KEY }}
        EOF
        echo "✅ Arquivo .env criado"

    - name: Step 1 - Get Last 30 Days Results
      env:
        BETSAPI_API_KEY: ${{ secrets.BETS_API_KEY }}
      run: |
        echo "=== 1. Coletando resultados dos últimos 30 dias ==="
        python get_matches_last30.py
        echo "✅ Resultados históricos coletados"

    - name: Step 2 - Monitor Upcoming Matches
      env:
        BETSAPI_API_KEY: ${{ secrets.BETS_API_KEY }}
      run: |
        echo "=== 2. Monitorando jogos próximos 3 dias ==="
        python monitor.py
        echo "✅ Jogos futuros coletados"

    - name: Step 3 - Identify Good Bets
      run: |
        echo "=== 3. Identificando apostas boas ==="
        python db_get_bets.py
        echo "✅ Apostas identificadas"

    - name: Step 4 - Check Bet Results
      run: |
        echo "=== 4. Verificando resultados das apostas ==="
        python db_get_bet_results.py
        echo "✅ Resultados verificados"

    - name: Step 5 - Send Telegram Notifications
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "=== 5. Enviando notificações Telegram ==="
        python send_telegram.py
        echo "✅ Notificações enviadas"

    - name: Check for database changes
      if: always()
      id: check-changes
      run: |
        git status
        if git diff --name-only | grep -E '\.(db|sqlite|json)$' || git diff --name-only | grep 'data/' || git ls-files --others --exclude-standard | grep -E '\.(db|sqlite|json)$'; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "✅ Mudanças detectadas no banco de dados"
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
          echo "❌ Nenhuma mudança detectada no banco de dados"
        fi

    - name: Commit and push database changes
      if: always() && steps.check-changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add *.db *.sqlite *.json data/ 2>/dev/null || true
        
        if git diff --staged --quiet; then
          echo "❌ Nenhuma mudança para commitar"
          exit 0
        fi
        
        git commit -m "🤖 Auto-update database: $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin HEAD:${{ github.ref_name }}
        echo "✅ Banco de dados atualizado e push realizado"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bot-data-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          *.log
          *.db
          *.sqlite
          *.json
          data/
        retention-days: 3

    - name: Notify execution status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Pipeline completo executado com sucesso"
          echo "::notice::Bot executado com sucesso - Todos os 5 passos concluídos"
        else
          echo "❌ Falha no pipeline de execução"
          echo "::error::Falha na execução do bot - Verifique os logs dos steps"
        fi